services:
  postgres:
    image: postgres
    container_name: chatapp-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - chatapp-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: chatapp-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - chatapp-redis:/data

volumes:
  chatapp-postgres:
  chatapp-redis:
